version: '2'
services:
  postfix:
    image: wailram/postfix:latest
    environment:
      SMTP_SERVER: ${IP}
      SERVER_HOSTNAME: ${DOMAIN_NAME}
      DESTINATION: ${DESTINATION}
    expose:
    - "25"
    - "587"
    env_file:
      - .env
    restart: always
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
